### PR TITLE
Revert to navigation bar on scanner screen

### LINKED ISSUE #92: iPhone X layout issues
Looks like the changes in #83 did not work fully as expected. On iPhone X the flash icon is vertically aligned center and the Auto/manual button is vertically aligned in the bottom. Not sure which one of them that is most corrrect, but... Added a screenshot:

img_ead76fef4674-1

### PR DESCRIPTION
**Pull request by justJS**
As per #92, this reverts to using the default navigation bar (with a visual effect view) on the scanner screen.

Note: The status bar is now visible again to avoid empty space on iPhone X, iPhone X🅂, iPhone X🅂 Max, and iPhone X🅁.

(Closes #92)

Original VS New (this PR):
simulator screen shot - iphone xs - 2018-11-30 at 19 02 21

### CODE REVIEW

File: WeScan/Edit/EditScanViewController.swift [hunk 1]
```diff
@@ -83,7 +83,6 @@ final class EditScanViewController: UIViewController {
     
     override func viewWillAppear(_ animated: Bool) {
         super.viewWillAppear(animated)
-        navigationController?.setNavigationBarHidden(false, animated: false)
     }
```
Comment (WeTransferOSSBot) [inline WeScan/Edit/EditScanViewController.swift]: <table data-meta="generated_by_danger">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/WeTransfer/WeScan/blob/3ad802a76f93426a8e4a73a0362fc37edebbe773/WeScan/Edit/EditScanViewController.swift#L86"></span>Override methods which only call super can be removed</td>
    </tr>
  </tbody>
</table>

**Comment by justJS** [comment]
Fixed the issues @AvdLee 🙂

**Comment by justJS** [comment]
I've resolved the merge conflicts that happened after merging other pull requests 👍

**Comment by justJS** [comment]
I believe we're waiting for a final review by @AvdLee then this should also be good to go! 🙂

**Comment by justJS** [comment]
Updated branch as requested by Github.

**Comment by mboeddeker** [comment]
Please merge that

File: WeScan/Scan/ScannerViewController.swift [hunk 2]
```diff
@@ -73,25 +73,40 @@ final class ScannerViewController: UIViewController {
...
-        navigationController?.setNavigationBarHidden(true, animated: false)
+        
+        let statusBarHeight = UIApplication.shared.statusBarFrame.size.height
+        let visualEffectRect = self.navigationController?.navigationBar.bounds.insetBy(dx: 0, dy: -(statusBarHeight)).offsetBy(dx: 0, dy: -statusBarHeight)
+        
+        visualEffectView.frame = visualEffectRect ?? CGRect.zero
+
+        navigationController?.navigationBar.isTranslucent = true
+        navigationController?.navigationBar.setBackgroundImage(UIImage(), for: .default)
+        navigationController?.navigationBar.addSubview(visualEffectView)
```
Comment (Boris-Em) [inline WeScan/Scan/ScannerViewController.swift]: We should probably not add subviews in `viewWillAppear` since it may be called multiple times. `viewDidLoad` seems more appropriate.

File: WeScan/Scan/ScannerViewController.swift [hunk 3]
```diff
@@ -73,25 +73,40 @@ final class ScannerViewController: UIViewController {
...
         captureSessionManager?.start()
         UIApplication.shared.isIdleTimerDisabled = true
-        navigationController?.setNavigationBarHidden(true, animated: false)
+        
+        let statusBarHeight = UIApplication.shared.statusBarFrame.size.height
+        let visualEffectRect = self.navigationController?.navigationBar.bounds.insetBy(dx: 0, dy: -(statusBarHeight)).offsetBy(dx: 0, dy: -statusBarHeight)
+        
+        visualEffectView.frame = visualEffectRect ?? CGRect.zero
+
+        navigationController?.navigationBar.isTranslucent = true
```
Comment (Boris-Em) [inline WeScan/Scan/ScannerViewController.swift]: We set `navigationController?.navigationBar.isTranslucent` to 2 different values (`true`, and `false`), in 3 different places: `viewDidLoad`, `viewWillAppear` and `viewDidLayoutSubviews`. This should only be set once and probably in `viewDidLoad`.
This is probably true for the other properties as well

File: WeScan/Scan/ScannerViewController.swift [hunk 4]
```diff
@@ -73,25 +73,40 @@ final class ScannerViewController: UIViewController {
...
         CaptureSession.current.isEditing = false
         quadView.removeQuadrilateral()
         captureSessionManager?.start()
         UIApplication.shared.isIdleTimerDisabled = true
-        navigationController?.setNavigationBarHidden(true, animated: false)
+        
+        let statusBarHeight = UIApplication.shared.statusBarFrame.size.height
+        let visualEffectRect = self.navigationController?.navigationBar.bounds.insetBy(dx: 0, dy: -(statusBarHeight)).offsetBy(dx: 0, dy: -statusBarHeight)
+        
+        visualEffectView.frame = visualEffectRect ?? CGRect.zero
```
Comment (Boris-Em) [inline WeScan/Scan/ScannerViewController.swift]: Shouldn't this happen in `viewDidLayoutSubviews` since the frame of the `navigationController` can change after the view appeared?

File: WeScan/Scan/ScannerViewController.swift (hunk 2 above)
Comment (justJS) [reply WeScan/Scan/ScannerViewController.swift]: Hey, this is because we don't want the blur effect to be shown on other screens. It's removed in `viewWillDisappear`.

File: WeScan/Scan/ScannerViewController.swift (hunk 3 above)
Comment (justJS) [reply WeScan/Scan/ScannerViewController.swift]: It's only being set in the initial setup (`setupNavigationBar`) and in `viewWillAppear`/`viewWillDisappear`, because otherwise the property would stay the same after navigating to a different screen such as the edit screen.

File: WeScan/Scan/ScannerViewController.swift (hunk 4 above)
Comment (justJS) [reply WeScan/Scan/ScannerViewController.swift]: That's a good idea - I'll do that.

**Comment by justJS** [comment]
Hey @Boris-Em, thanks for the suggestions. I've commented on some to clarify the current behavior and resolved the issue of the frame being set before `viewDidLayoutSubviews`. Let me know what you think 🙂

File: WeScan/Scan/ScannerViewController.swift (hunk 3 above)
Comment (Boris-Em) [reply WeScan/Scan/ScannerViewController.swift]: Do we need to set it in `setupNavigationBar` (`viewDidLoad`) since it's called it `viewWillAppear`?

File: WeScan/Scan/ScannerViewController.swift (hunk 2 above)
Comment (Boris-Em) [reply WeScan/Scan/ScannerViewController.swift]: Don't we add it twice right now? On `viewDidLoad` via `setupNavigationBar` and here on `viewWillAppear`?

**Comment by justJS** [comment]
My bad! I've resolved both issues @Boris-Em.

File: WeScan/Scan/ScannerViewController.swift (hunk 3 above)
Comment (justJS) [reply WeScan/Scan/ScannerViewController.swift]: Fixed!

File: WeScan/Scan/ScannerViewController.swift (hunk 2 above)
Comment (justJS) [reply WeScan/Scan/ScannerViewController.swift]: Fixed!

**Comment by justJS** [comment]
🎉 Are we ready to merge?

**Comment by Boris-Em** [comment]
Ready to merge!

**Comment by justJS** [comment]
Yay! 🎊
