### PR TITLE
Fix Rotation & Enhance Button

### LINKED ISSUE #144: Toolbar Enhance Button and Rotation on Edit Screen(Bug)
I have used the version
pod 'WeScan', '>= 0.9'

This is first time I am posting an issue so please ignore if it seems derogatory comment.

1). When I capture an image and come to edit screen bottom enhance button is not working for the first time click.
2). While clicking 2 times that button it works than rotate the image, the image gets change to original image.
3). Once I rotate first and do apply the enhancement it is working for every-time rotation after that.

To get clear idea I am attaching the video file of this issue.

Thanks,
Aashi Shaikh.

[Wescan_issue.mov.zip](https://github.com/WeTransfer/WeScan/files/2965142/Wescan_issue.mov.zip)

### PR DESCRIPTION
**Pull request by Boris-Em**
As reported in #144, we had an issue with the state of the `isCurrentlyDisplayingEnhancedImage` property.
Closes #144.

### CODE REVIEW

File: WeScan/Review/ReviewViewController.swift [hunk 1]
```diff
@@ -126,15 +126,14 @@ final class ReviewViewController: UIViewController {
     @objc private func toggleEnhancedImage() {
         guard enhancedImageIsAvailable else { return }
         
+        isCurrentlyDisplayingEnhancedImage.toggle()
```
Comment (AvdLee) [inline WeScan/Review/ReviewViewController.swift]: Love the use of `toggle()`, up to date with latest Swift features 🚀

File: WeScan/Review/ReviewViewController.swift [hunk 2]
```diff
@@ -126,15 +126,14 @@ final class ReviewViewController: UIViewController {
...
         reloadImage()
         
         if isCurrentlyDisplayingEnhancedImage {
-            enhanceButton.tintColor = .white
-        } else {
             enhanceButton.tintColor = UIColor(red: 64 / 255, green: 159 / 255, blue: 255 / 255, alpha: 1.0)
+        } else {
```
Comment (AvdLee) [inline WeScan/Review/ReviewViewController.swift]: Can we maybe write a test to reproduce this issue how it was, to make sure we don't introduce it again?

Comment (Boris-Em) [reply WeScan/Review/ReviewViewController.swift]: This is a good idea.

File: WeScanTests/ReviewViewControllerTests.swift [hunk 3]
```diff
@@ -88,5 +94,14 @@ final class ReviewViewControllerTests: FBSnapshotTestCase {
         
         FBSnapshotVerifyView(vc.imageView)
```
Comment (WeTransferOSSBot) [inline WeScanTests/ReviewViewControllerTests.swift]: <table data-meta="generated_by_danger">
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/WeTransfer/WeScan/blob/9b4928415c80098dad7dfe1ba0f11ad1db32206a/WeScanTests/ReviewViewControllerTests.swift#L95"></span><strong>WeScanTests.ReviewViewControllerTests</strong>: testImageIsCorrectlyRotated360, failed - Test ran in record mode. Reference image is now saved. Disable record mode to perform an actual snapshot comparison!  <br />  <a href="https://github.com/WeTransfer/WeScan/blob/9b4928415c80098dad7dfe1ba0f11ad1db32206a/WeScanTests/ReviewViewControllerTests.swift#L95">WeScanTests/ReviewViewControllerTests.swift#L95</a></td>
    </tr>
  </tbody>
</table>

File: WeScanTests/ReviewViewControllerTests.swift [hunk 4]
```diff
@@ -88,5 +94,14 @@ final class ReviewViewControllerTests: FBSnapshotTestCase {
...
     }
+    
+    func testEnhancedImage() {
+        let results = ImageScannerResults(originalImage: demoImage, scannedImage: demoImage, enhancedImage: enhancedDemoImage, doesUserPreferEnhancedImage: false, detectedRectangle: demoQuad)
+        let viewController = ReviewViewController(results: results)
+        viewController.viewDidLoad()
+        
+        viewController.toggleEnhancedImage()
+        FBSnapshotVerifyView(viewController.imageView)
```
Comment (WeTransferOSSBot) [inline WeScanTests/ReviewViewControllerTests.swift]: <table data-meta="generated_by_danger">
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/WeTransfer/WeScan/blob/9b4928415c80098dad7dfe1ba0f11ad1db32206a/WeScanTests/ReviewViewControllerTests.swift#L104"></span><strong>WeScanTests.ReviewViewControllerTests</strong>: testEnhancedImage, failed - Test ran in record mode. Reference image is now saved. Disable record mode to perform an actual snapshot comparison!  <br />  <a href="https://github.com/WeTransfer/WeScan/blob/9b4928415c80098dad7dfe1ba0f11ad1db32206a/WeScanTests/ReviewViewControllerTests.swift#L104">WeScanTests/ReviewViewControllerTests.swift#L104</a></td>
    </tr>
  </tbody>
</table>

Comment (WeTransferOSSBot) [inline WeScanTests/ReviewViewControllerTests.swift]: <table data-meta="generated_by_danger">
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/WeTransfer/WeScan/blob/029c8698136b560477fdbf099d0bef8be874a2f5/WeScanTests/ReviewViewControllerTests.swift#L104"></span><strong>WeScanTests.ReviewViewControllerTests</strong>: testEnhancedImage, failed - Snapshot comparison failed: Optional(Error Domain=FBSnapshotTestControllerErrorDomain Code=1 “Unable to load reference image.” UserInfo={NSLocalizedFailureReason=Reference image not found. You need to run the test in record mode, NSLocalizedDescription=Unable to load reference image., FBReferenceImageFilePathKey=/Users/travis/build/WeTransfer/WeScan/WeScanTests/ReferenceImages_64/WeScanTests.ReviewViewControllerTests/testEnhancedImage@2x.png})  <br />  <a href="https://github.com/WeTransfer/WeScan/blob/029c8698136b560477fdbf099d0bef8be874a2f5/WeScanTests/ReviewViewControllerTests.swift#L104">WeScanTests/ReviewViewControllerTests.swift#L104</a></td>
    </tr>
  </tbody>
</table>

Comment (WeTransferOSSBot) [inline WeScanTests/ReviewViewControllerTests.swift]: <table data-meta="generated_by_danger">
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/WeTransfer/WeScan/blob/029c8698136b560477fdbf099d0bef8be874a2f5/WeScanTests/ReviewViewControllerTests.swift#L104"></span><strong>WeScanTests.ReviewViewControllerTests</strong>: testEnhancedImage, failed - Snapshot comparison failed: Optional(Error Domain=FBSnapshotTestControllerErrorDomain Code=1 “Unable to load reference image.” UserInfo={NSLocalizedFailureReason=Reference image not found. You need to run the test in record mode, NSLocalizedDescription=Unable to load reference image., FBReferenceImageFilePathKey=/Users/travis/build/WeTransfer/WeScan/WeScanTests/ReferenceImages_32/WeScanTests.ReviewViewControllerTests/testEnhancedImage@2x.png})  <br />  <a href="https://github.com/WeTransfer/WeScan/blob/029c8698136b560477fdbf099d0bef8be874a2f5/WeScanTests/ReviewViewControllerTests.swift#L104">WeScanTests/ReviewViewControllerTests.swift#L104</a></td>
    </tr>
  </tbody>
</table>

**Comment by PrincessMine** [comment]
Hello team,

When we are supposed to get this change live on the repository. Expecting this change live asap as you guys putting great efforts on my request.

Thanks.

**Comment by AvdLee** [comment]
@PrincessMine just pushed a fix for the tests and I'll merge it in afterwards. Sorry for the delay!
